# Dans un fichier .github/workflows/script-mirror.yaml
name: Repo sync with Cloud π Native

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  mirror:
    name: Sync repo with Cloud π Native
    runs-on: ubuntu-latest
    steps:
      - name: Checks-out repository
        uses: actions/checkout@v3
      - name: Send a sync request to DSO api
        run: |
          sh ./ci/mirror.sh \
            -a "https://gitlab.apps.ocp4-7.infocepo.com" \
            -b "master" \
            -g "${{ secrets.GITLAB_TRIGGER_TOKEN }}" \
            -i "33"
